version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: econ-strategy-dw_db
    restart: always
    environment:
      POSTGRES_DB: econ_strategy_dw
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  postgres_data:

networks:
  postgres_network: